### ISSUE TITLE
JAR manifest should list Main-Class

### ISSUE THREAD

**Issue by DoomTay** [drewnoakes/metadata-extractor#176]
I made a .bat file for outputting image data from the program .jar, but from 2.9.0 onwards, feeding an image to this .bat produces an error.

With a PSD such as BlazRobar Thinking Head Icon Set.psd, the error looks like this
```
Exception in thread "main" java.lang.NoClassDefFoundError: com/adobe/xmp/XMPException
        at com.drew.metadata.photoshop.PhotoshopReader.extract(Unknown Source)
        at com.drew.metadata.photoshop.PsdReader.extract(Unknown Source)
        at com.drew.imaging.psd.PsdMetadataReader.readMetadata(Unknown Source)
        at com.drew.imaging.ImageMetadataReader.readMetadata(Unknown Source)
        at com.drew.imaging.ImageMetadataReader.readMetadata(Unknown Source)
        at com.drew.imaging.ImageMetadataReader.main(Unknown Source)
Caused by: java.lang.ClassNotFoundException: com.adobe.xmp.XMPException
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        ... 6 more
```

With a JPG like adobeJpeg1.jpg the error is only slightly different
```
Exception in thread "main" java.lang.NoClassDefFoundError: com/adobe/xmp/XMPException
        at com.drew.imaging.jpeg.JpegMetadataReader.<clinit>(Unknown Source)
        at com.drew.imaging.ImageMetadataReader.readMetadata(Unknown Source)
        at com.drew.imaging.ImageMetadataReader.readMetadata(Unknown Source)
        at com.drew.imaging.ImageMetadataReader.main(Unknown Source)
Caused by: java.lang.ClassNotFoundException: com.adobe.xmp.XMPException
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        ... 4 more
```

**Comment by drewnoakes** [comment]
You need to make sure the XMP .jar file is available on the classpath.

**Comment by DoomTay** [comment]
I looked into how to do that and discovered that the Class-Path header is missing from MANIFEST.MF, unlike with 2.8.1. Sadly, fixing that has not helped.

**Comment by drewnoakes** [comment]
Do you have `xmpcore-5.1.2.jar` on your computer? I think that if it's in the same folder as `metadata-extractor.jar` then everything should just work.

With respect to including it in a classpath within the jar's manifest, I'm not too sure about this. Perhaps someone else can comment. If you use the Maven-built jar, I'd expect it's correctly set up as Maven is aware of the dependency, though I'm not an expert on Maven.

**Comment by DoomTay** [comment]
I do have xmpcore-5.1.2.jar in the same folder as the metadata extractor jar. I even re-downloaded both from the latest release just to be sure, yet the problem persists.

This did not happen with 2.8.1

**Comment by DoomTay** [comment]
I am sorry to say the problem still persists with 2.9.1

**Comment by drewnoakes** [comment]
What if you

**Comment by drewnoakes** [comment]
Thanks for the batch file contents. That was helpful. As an aside, is `>` character in your `java ...` line causing the rest of the line to be ignored?

The XMPCore messages in your original post led me down the wrong path I think. This doesn't seem to have anything to do with XMPCore or the `CLASSPATH`. Rather recent builds of the .jar files don't have `Main-Class` defined, so the jars are not executable.

I'll get this fixed for the next release. Some relevant help in [this SO answer](http://stackoverflow.com/a/9689877/24874).
