### ISSUE TITLE
java.lang.VerifyError on Android Jelly Bean devices

### ISSUE THREAD

**Issue by sungjin0213** [drewnoakes/metadata-extractor#186]
This library is working fine on Android Lollipop and Marshmallow, but on Jelly Bean devices, it's crashing with "java.lang.VerifyError: com/drew/metadata/xmp/XmpReader" when trying to Metadata metadata = ImageMetadataReader.readMetadata(bufferedInputStream); I tried to change to just input stream, but it didn't change this behavior. Would you investigate and fix this?

```
java.lang.VerifyError: com/drew/metadata/xmp/XmpReader
    at com.drew.imaging.jpeg.JpegMetadataReader.<clinit>(JpegMetadataReader.java:55)
	at com.drew.imaging.ImageMetadataReader.readMetadata(ImageMetadataReader.java:112)
    at com.drew.imaging.ImageMetadataReader.readMetadata(ImageMetadataReader.java:90)
    at com.mypackage.name.utilities.MyImageUtils$1.run(MyImageUtils.java:37)
    at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:230)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
    at java.lang.Thread.run(Thread.java:841)
```

**Comment by TSGames** [comment]
Hi Sung, are you sure you've added the XMPLibrary to your Project in build.gradle?
`dependencies {
    compile files('libs/xmpcore-5.1.2.jar')
}
`
I'm using the library back since Android 2.x and it's working fine across all platforms.

Regards
Torsten

**Comment by sungjin0213** [comment]
That was it! I didn't include xmpcore-5.1.2.jar. Somehow it worked on newer devices... hmm weird. Thanks!

**Comment by drewnoakes** [comment]
Glad you got it working, and thanks to @TSGames for the guidance. I haven't done any Android development.

If you have some information to share regarding the use of the library under Android, perhaps it would make a good addition to the wiki. Feel free to make an 'Android' page and include some info there.
