### ISSUE TITLE
Fatal Exception: org.w3c.dom.DOMException

### ISSUE THREAD

**Issue by imakhalova** [drewnoakes/metadata-extractor#205]
Getting some crash reports from users that upload photos and I extract metadata before uploading it (have no repro myself, so I'm not sure what is so special in this photo) 
Fatal Exception: org.w3c.dom.DOMException: Only one root element allowed
       at org.apache.harmony.xml.dom.DocumentImpl.insertChildAt(DocumentImpl.java:421)
       at org.apache.harmony.xml.dom.InnerNodeImpl.appendChild(InnerNodeImpl.java:52)
       at org.apache.harmony.xml.parsers.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:273)
       at org.apache.harmony.xml.parsers.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:128)
       at com.adobe.xmp.impl.XMPMetaParser.parse(Unknown Source)
       at com.adobe.xmp.impl.XMPMetaParser.parse(Unknown Source)
       at com.adobe.xmp.impl.XMPMetaParser.parseXml(Unknown Source)
       at com.adobe.xmp.impl.XMPMetaParser.parse(Unknown Source)
       at com.adobe.xmp.XMPMetaFactory.getSchemaRegistry(Unknown Source)
       at com.adobe.xmp.XMPMetaFactory.getSchemaRegistry(Unknown Source)
       at com.drew.metadata.xmp.XmpReader.getSegmentTypes(Unknown Source)
       at com.drew.metadata.xmp.XmpReader.getSegmentTypes(Unknown Source)
       at com.drew.metadata.xmp.XmpReader.getSegmentTypes(Unknown Source)
       at com.drew.imaging.jpeg.JpegMetadataReader.readMetadata(Unknown Source)
       at com.drew.imaging.jpeg.JpegMetadataReader.readMetadata(Unknown Source)
       at com.drew.imaging.jpeg.JpegMetadataReader.readMetadata(Unknown Source)
       at com.drew.imaging.jpeg.JpegMetadataReader.readMetadata(Unknown Source)
       at com.drew.imaging.ImageMetadataReader.readMetadata(Unknown Source)
       at com.drew.imaging.ImageMetadataReader.readMetadata(Unknown Source)

**Comment by drewnoakes** [comment]
Strange. Might be a bug in XMPCore. That stack trace looks strange too -- `getSegmentTypes` doesn't call `getSchemaRegistry`. In fact, nothing in `XmpReader` does.

Without an image there's not much I can do. Please re-open if you can attach an image that reproduces the issue.

**Comment by imakhalova** [comment]
This stack trace is not fully correct bcz code was obfuscated, but it doesn't cancel the crash itself.
I think I can figure out exact trace
