### ISSUE TITLE
Fatal Exception: java.lang.IllegalArgumentException: PNG chunk type identifier may only contain alphabet 

### ISSUE THREAD

**Issue by imakhalova** [drewnoakes/metadata-extractor#206]
Stack trace might be deobfuscated a little bit with different method names
Fatal Exception: java.lang.IllegalArgumentException: PNG chunk type identifier may only contain alphabet characters
       at com.drew.imaging.png.PngChunkType.validateBytes(Unknown Source)
       at com.drew.imaging.png.PngChunkType.(Unknown Source)
       at com.drew.imaging.png.PngChunkReader.extract(Unknown Source)
       at com.drew.imaging.png.PngMetadataReader.readMetadata(Unknown Source)
       at com.drew.imaging.ImageMetadataReader.readMetadata(Unknown Source)
       at com.drew.imaging.ImageMetadataReader.readMetadata(Unknown Source)

**Comment by drewnoakes** [comment]
As the error suggests, the file contains invalid PNG data. Can you provide an image to repro the problem?

**Comment by imakhalova** [comment]
I don't have user's picture (only crashes in crash analytics tool).
But shouldn't it throw some handled exception (PngProcessingException) to avoid crashing?

**Comment by drewnoakes** [comment]
Sounds good. Should be easy to reproduce that in a unit test. Can you make a PR?

**Comment by imakhalova** [comment]
Sure
