### ISSUE TITLE
Fatal Exception: java.lang.RuntimeException: Undefined Prefix: attr in org.kxml2.io.KXmlParser

### ISSUE THREAD

**Issue by imakhalova** [drewnoakes/metadata-extractor#208]
One more interesting crash stack (no picture, only deobfuscated stack trace from crash analytics)
Fatal Exception: java.lang.RuntimeException: Undefined Prefix: attr in org.kxml2.io.KXmlParser@dccdeeb
       at org.kxml2.io.KXmlParser.adjustNsp(KXmlParser.java:260)
       at org.kxml2.io.KXmlParser.parseStartTag(KXmlParser.java:1152)
       at org.kxml2.io.KXmlParser.next(KXmlParser.java:372)
       at org.kxml2.io.KXmlParser.nextToken(KXmlParser.java:317)
       at org.apache.harmony.xml.parsers.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:328)
       at org.apache.harmony.xml.parsers.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:295)
       at org.apache.harmony.xml.parsers.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:295)
       at org.apache.harmony.xml.parsers.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:128)
       at com.adobe.xmp.impl.XMPMetaParser.parse(Unknown Source)
       at com.adobe.xmp.impl.XMPMetaParser.parse(Unknown Source)
       at com.adobe.xmp.impl.XMPMetaParser.parseXml(Unknown Source)
       at com.adobe.xmp.impl.XMPMetaParser.parse(Unknown Source)
       at com.adobe.xmp.XMPMetaFactory.getSchemaRegistry(Unknown Source)
       at com.adobe.xmp.XMPMetaFactory.getSchemaRegistry(Unknown Source)
       at com.drew.metadata.xmp.XmpReader.getSegmentTypes(Unknown Source)
       at com.drew.metadata.xmp.XmpReader.getSegmentTypes(Unknown Source)
       at com.drew.metadata.xmp.XmpReader.getSegmentTypes(Unknown Source)
       at com.drew.imaging.jpeg.JpegMetadataReader.readMetadata(Unknown Source)
       at com.drew.imaging.jpeg.JpegMetadataReader.readMetadata(Unknown Source)
       at com.drew.imaging.jpeg.JpegMetadataReader.readMetadata(Unknown Source)
       at com.drew.imaging.jpeg.JpegMetadataReader.readMetadata(Unknown Source)
       at com.drew.imaging.ImageMetadataReader.readMetadata(Unknown Source)
       at com.drew.imaging.ImageMetadataReader.readMetadata(Unknown Source)

**Comment by drewnoakes** [comment]
As in #205, without an image there isn't much we can do here. We can _speculate_ that the image contains invalid XML.

We could wrap the call to XML parsing with a `try/catch (Exception)` but that might hide legitimate problems and feels like a bad idea.

Is it possible the obfuscator is breaking the code's logic? I haven't seen reports like these two before, and both involve obfuscated code.

Closing this for now. Can't see a path forward, sorry.

**Comment by imakhalova** [comment]
One more around that, just to keep track of those issues
Fatal Exception: java.lang.RuntimeException: Undefined Prefix: xMlns in org.kxml2.io.KXmlParser@febdc48
       at org.kxml2.io.KXmlParser.adjustNsp(KXmlParser.java:260)
       at org.kxml2.io.KXmlParser.parseStartTag(KXmlParser.java:1152)
       at org.kxml2.io.KXmlParser.next(KXmlParser.java:372)
       at org.kxml2.io.KXmlParser.nextToken(KXmlParser.java:317)
       at org.apache.harmony.xml.parsers.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:328)
       at org.apache.harmony.xml.parsers.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:295)
       at org.apache.harmony.xml.parsers.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:128)
       at com.adobe.xmp.impl.XMPMetaParser.parse(Unknown Source)
       at com.adobe.xmp.impl.XMPMetaParser.parse(Unknown Source)
       at com.adobe.xmp.impl.XMPMetaParser.parseXml(Unknown Source)
       at com.adobe.xmp.impl.XMPMetaParser.parse(Unknown Source)
       at com.adobe.xmp.XMPMetaFactory.getSchemaRegistry(Unknown Source)
       at com.adobe.xmp.XMPMetaFactory.getSchemaRegistry(Unknown Source)
       at com.drew.metadata.xmp.XmpReader.getSegmentTypes(Unknown Source)
       at com.drew.metadata.xmp.XmpReader.getSegmentTypes(Unknown Source)
       at com.drew.metadata.xmp.XmpReader.getSegmentTypes(Unknown Source)
       at com.drew.imaging.jpeg.JpegMetadataReader.readMetadata(Unknown Source)
       at com.drew.imaging.jpeg.JpegMetadataReader.readMetadata(Unknown Source)
       at com.drew.imaging.jpeg.JpegMetadataReader.readMetadata(Unknown Source)
       at com.drew.imaging.jpeg.JpegMetadataReader.readMetadata(Unknown Source)
       at com.drew.imaging.ImageMetadataReader.readMetadata(Unknown Source)
       at com.drew.imaging.ImageMetadataReader.readMetadata(Unknown Source)

**Comment by kwhopper** [comment]
"Undefined Prefix: xMlns" seems to indicate a node or attribute has a prefix of "xMlns" - but that prefix wasn't previously defined. I suspect it was supposed to be lower case. XML strictly enforces case sensitivity, so this is just bad XML and Java's DocumentBuilder (used by XmpCore to parse XML) isn't going to let it through.

**Comment by drewnoakes** [comment]
Well spotted @kwhopper.

Could your obfuscator be renaming something that's interfering with XML handling?

**Comment by imakhalova** [comment]
I've got plenty of those: 
java.lang.RuntimeException: Undefined Prefix: stEvt in org.kxml2.io.KXmlParser
java.lang.RuntimeException: Undefined Prefix: xil�s in org.kxml2.io.KXmlParser
java.lang.RuntimeException: Undefined Prefix: xapMM in org.kxml2.io.KXmlParser

It's not obfuscator problem, it doesn't do anything with incoming data.

Can you clarify please what do you mean by bad XML? Some picture has XMP data that can't be parsed as XML has unexpected prefixes?

Is it possible that problem is in locale (not considered somewhere)? Some phone settings?

**Comment by kwhopper** [comment]
Is it at all possible to get a sample of one of the baddies? That would definitely help us nail this down.

The exception allows me to make a guess though, and it's similar to the last guess -- some nodes are declaring themselves as in namespaces that haven't been previously declared. Note the structure of the example XMP document here:

[https://en.wikipedia.org/wiki/Extensible_Metadata_Platform](https://en.wikipedia.org/wiki/Extensible_Metadata_Platform)

Wherever you see attributes of "xmlns:" they are namespace declarations. Apparently some of your files have nodes in namespaces that haven't been declared yet.

But again, a sample would really help us figure this out. Thanks!

**Comment by drewnoakes** [comment]
Some XML libraries bind elements/attributes to JVM types. If that's the case here, and your obfuscator is renaming bound properties, then that could be the reason.

Otherwise we cannot help without a sample image.

You could try running your program before obfuscating it to verify.

**Comment by imakhalova** [comment]
Thank you guys for your help, 
I wish I had picture with repro myself. It would simplify investigation a lot. But I've got only crash reports.

I will turn off deobfuscator for classes within your library. But Adobe library can be obfuscated itself.

I think that we might have misconfigured XMLs within some pictures (who knows, may be some phone models set wrong data on their camera apps or may be picture went through some picture editor who lost data). I just didn't expect XML parser to throw RuntimException for that kind of error (SAXException would be more expected).

And I see that I'm not the only one who is struggling with this problem:
https://android.googlesource.com/platform/tools/base/+/1cc4685af45822f90fbb289eb06a1a37893f2a52/sdk-common/src/main/java/com/android/ide/common/resources/ValidatingResourceParser.java ( line 99)
