### ISSUE TITLE
Image causes NegativeArraySizeException

### ISSUE THREAD

**Issue by davidekholm** [drewnoakes/metadata-extractor#260]
This attached image triggers a NegativeArraySizeException in the current metadata-extractor library (worked in the old version I was using before in jAlbum. Here's the stack trace:

Caused by: java.lang.NegativeArraySizeException
        at com.drew.metadata.jpeg.JpegDhtReader.getBytes(JpegDhtReader.java:88)
        at com.drew.metadata.jpeg.JpegDhtReader.extract(JpegDhtReader.java:77)
        at com.drew.metadata.jpeg.JpegDhtReader.readJpegSegments(JpegDhtReader.java:50)
        at com.drew.imaging.jpeg.JpegMetadataReader.processJpegSegmentData(JpegMetadataReader.java:134)
        at com.drew.imaging.jpeg.JpegMetadataReader.process(JpegMetadataReader.java:126)
        at com.drew.imaging.jpeg.JpegMetadataReader.readMetadata(JpegMetadataReader.java:77)
        at com.drew.imaging.jpeg.JpegMetadataReader.readMetadata(JpegMetadataReader.java:84)
        at com.drew.imaging.ImageMetadataReader.readMetadata(ImageMetadataReader.java:111)
        at com.drew.imaging.ImageMetadataReader.readMetadata(ImageMetadataReader.java:161)
        at se.datadosen.jalbum.AlbumObjectMetadata.<init>(AlbumObjectMetadata.java:39)

[lydia-harper-212169.zip](https://github.com/drewnoakes/metadata-extractor/files/848316/lydia-harper-212169.zip)

**Comment by drewnoakes** [comment]
@Nadahar could you take a look at this? Seems like another signed byte issue.

**Comment by Nadahar** [comment]
@drewnoakes Will do. I hope it's not...

**Comment by drewnoakes** [comment]
Thanks. I'm uploading the image for regression testing.

**Comment by Nadahar** [comment]
I don't get any error when testing this image with current master. @davidekholm Did you use the latest version?

**Comment by drewnoakes** [comment]
`master` is ahead of Maven. Maybe it's time to do a release :)

**Comment by Nadahar** [comment]
@drewnoakes That might be, but as far as I can see 84462040c86f106db0257bfc27e84238ef85914e (which fixes this) was in ```2.10.1```.

**Comment by drewnoakes** [comment]
True, I skip-read 651d9c0bf1b which is also a signed byte issue, but it's actually in `GifReader`.

So yes, David are you using [2.10.1](https://github.com/drewnoakes/metadata-extractor/releases/tag/2.10.1)?

**Comment by Nadahar** [comment]
I checked out tag ```2.10.1``` just to be absolutely sure, and it reads it just fine.

**Comment by davidekholm** [comment]
I've been using 2.10.0. I'll update to 2.10.1 now. Thanks!

**Comment by Nadahar** [comment]
Great 😌

**Comment by davidekholm** [comment]
Stupid question: How do I make my local version up to date with the Git repository? I'm using Netbeans and couldn't figure out any other way but grabbing the whole project as a zip file again.

**Comment by Nadahar** [comment]
@davidekholm You need to clone the repository using Git to be able to update it. If you do that, you can update it with ```git fetch``` and ```git pull```. See for example [this guide](http://rogerdudler.github.io/git-guide/).

If you have just downloaded the zip file, you don't have a local git repository and there's no way to update it other than to re-download and overwrite the existing files.

**Comment by drewnoakes** [comment]
Closing this for now. Shout if you still have a problem.

**Comment by davidekholm** [comment]
Will do :-)
