### ISSUE TITLE
Caused by: java.lang.ClassNotFoundException: com.adobe.xmp.XMPException

### ISSUE THREAD

**Issue by chinanewer** [drewnoakes/metadata-extractor#284]
Exception in thread "main" java.lang.NoClassDefFoundError: com/adobe/xmp/XMPException
	at com.drew.imaging.jpeg.JpegMetadataReader.<clinit>(JpegMetadataReader.java:57)
	at com.drew.imaging.ImageMetadataReader.readMetadata(ImageMetadataReader.java:111)
	at com.drew.imaging.ImageMetadataReader.readMetadata(ImageMetadataReader.java:161)
	at Main.main(Main.java:17)
Caused by: java.lang.ClassNotFoundException: com.adobe.xmp.XMPException
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 4 more

**Comment by drewnoakes** [comment]
You must make sure the XMPCore JAR is available on the classpath.

**Comment by msetkowski** [comment]
Maybe a short comment - putting xmpcore on classpath is limited to some versions of that library. In version 6.1.10 (or maybe all 6.x) they have renamed package to com.adobe.internal.xmp
