### ISSUE TITLE
com.drew.lang.BufferBoundsException

### ISSUE THREAD

**Issue by chenlingmin** [drewnoakes/metadata-extractor#287]
```

com.drew.lang.BufferBoundsException: Attempt to read from beyond end of underlying data source (requested index: 6, requested count: 2, max index: 5)
	at com.drew.lang.ByteArrayReader.validateIndex(ByteArrayReader.java:86)
	at com.drew.lang.RandomAccessReader.getInt16(RandomAccessReader.java:210)

	at com.drew.imaging.tiff.TiffReader.processTiff(TiffReader.java:53)
	at com.drew.metadata.exif.ExifReader.extract(ExifReader.java:87)
	at com.drew.metadata.exif.ExifReader.extract(ExifReader.java:77)

	at com.drew.metadata.exif.ExifReader.readJpegSegments(ExifReader.java:64)	at com.drew.metadata.exif.ExifReader.readJpegSegments(ExifReader.java:64)
	at com.drew.imaging.jpeg.JpegMetadataReader.processJpegSegmentData(JpegMetadataReader.java:134)
	at com.drew.imaging.jpeg.JpegMetadataReader.processJpegSegmentData(JpegMetadataReader.java:134)
	at com.drew.imaging.jpeg.JpegMetadataReader.process(JpegMetadataReader.java:126)
	at com.drew.imaging.jpeg.JpegMetadataReader.process(JpegMetadataReader.java:126)
	at com.drew.imaging.jpeg.JpegMetadataReader.readMetadata(JpegMetadataReader.java:77)
	at com.drew.imaging.jpeg.JpegMetadataReader.readMetadata(JpegMetadataReader.java:77)
	at com.drew.imaging.jpeg.JpegMetadataReader.readMetadata(JpegMetadataReader.java:84)
	at com.drew.imaging.jpeg.JpegMetadataReader.readMetadata(JpegMetadataReader.java:84)
	at com.drew.imaging.ImageMetadataReader.readMetadata(ImageMetadataReader.java:111)
	at com.drew.imaging.ImageMetadataReader.readMetadata(ImageMetadataReader.java:111)
	at com.drew.imaging.ImageMetadataReader.readMetadata(ImageMetadataReader.java:89)	at com.drew.imaging.ImageMetadataReader.readMetadata(ImageMetadataReader.java:89)
	at 
```

**Comment by PaytonGarland** [comment]
Any chance you could provide an image that is throwing this error?

**Comment by drewnoakes** [comment]
Please provide a sample image that reproduces this problem, otherwise we can't help and will have to close this issue.

**Comment by payton** [comment]
Closing this issue as no sample image has been provided. @chenlingmin feel free to reopen if you are able to add a sample image.

**Comment by drewnoakes** [comment]
Looking at the stack trace, this must have been a corrupted JPEG containing a segment with correct preamble but nothing beyond that. I don't think there's much we could do here.

This _might_ help:

```diff
diff --git a/Source/com/drew/metadata/exif/ExifReader.java b/Source/com/drew/metadata/exif/ExifReader.java
index ffc77c67..b5c0a1ca 100644
--- a/Source/com/drew/metadata/exif/ExifReader.java
+++ b/Source/com/drew/metadata/exif/ExifReader.java
@@ -59,7 +59,7 @@ public class ExifReader implements JpegSegmentMetadataReader

         for (byte[] segmentBytes : segments) {
             // Filter any segments containing unexpected preambles
-            if (segmentBytes.length < JPEG_SEGMENT_PREAMBLE.length() || !new String(segmentBytes, 0, JPEG_SEGMENT_PREAMBLE.length()).equals(JPEG_SEGMENT_PREAMBLE))
+            if (segmentBytes.length <= JPEG_SEGMENT_PREAMBLE.length() || !new String(segmentBytes, 0, JPEG_SEGMENT_PREAMBLE.length()).equals(JPEG_SEGMENT_PREAMBLE))
                 continue;
             extract(new ByteArrayReader(segmentBytes), metadata, JPEG_SEGMENT_PREAMBLE.length());
         }
```
