### ISSUE TITLE
ExifReader throws java.lang.VerifyError: Bad type on operand stack

### ISSUE THREAD

**Issue by bytemedwb** [drewnoakes/metadata-extractor#309]
The class is invoked from Apache Tika 1.16

.  
This happens frequently on embedded images in Office documents.
Below is the stack trace.
Exception in thread "main" java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location:
    org/apache/tika/parser/image/ImageMetadataExtractor.parseRawExif([B)V @31: invokevirtual
  Reason:
    Type 'com/drew/lang/ByteArrayReader' (current frame, stack[1]) is not assignable to 'com/drew/lang/RandomAccessReader'
  Current Frame:
    bci: @31
    flags: { }
    locals: { 'org/apache/tika/parser/image/ImageMetadataExtractor', '[B', 'com/drew/metadata/Metadata', 'com/drew/metadata/exif/ExifReader' }
    stack: { 'com/drew/metadata/exif/ExifReader', 'com/drew/lang/ByteArrayReader', 'com/drew/metadata/Metadata', integer }
  Bytecode:
    0x0000000: bb00 2059 b700 214d bb00 2859 b700 294e
    0x0000010: 2dbb 002a 592b b700 2b2c 122c b600 2db6
    0x0000020: 002e 2a2c b600 17a7 0011 3a04 bb00 1959
    0x0000030: 122f 1904 b700 1bbf b1                 
  Exception Handler Table:
    bci [34, 39] => handler: 42
  Stackmap Table:
    full_frame(@42,{Object[#141],Object[#136],Object[#142],Object[#143]},{Object[#115]})
    same_frame(@56)

	at org.apache.tika.parser.jpeg.JpegParser.parse(JpegParser.java:58)
	at org.apache.tika.parser.CompositeParser.parse(CompositeParser.java:280)
Here is the entire document:
[DuterteLookingToDestroyImperialManila_AgenceFrance-Presse_JUN16_AJ.docx](https://github.com/drewnoakes/metadata-extractor/files/1536708/DuterteLookingToDestroyImperialManila_AgenceFrance-Presse_JUN16_AJ.docx)
Here is the embedded image
![dutertenew7](https://user-images.githubusercontent.com/3876300/33683017-79ffdd48-da97-11e7-84cc-4e0b15d0d8ca.jpg)

**Comment by bytemedwb** [comment]
Note.  This likely has something to do with the MS Word document.  Cutting the image out and pasting it back in caused the problem to go away.
Might be better problem submitted to Tika.

**Comment by bytemedwb** [comment]
Never mind.  Looks like issue was another dependency pulling in an old version of your library.
Eclipse was smart enough to resolve the issue.
