### ISSUE TITLE
NullpointerException when parsing GoPro MP4 videos

### ISSUE THREAD

**Issue by davidekholm** [drewnoakes/metadata-extractor#368]
When trying to extract metadata from GoPro MP4 videos, metatadata-extractor throws a NullpointerException:

Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at com.drew.metadata.mp4.Mp4MediaHandler.<init>(Mp4MediaHandler.java:50)
	at com.drew.metadata.mp4.media.Mp4MetaHandler.<init>(Mp4MetaHandler.java:36)
	at com.drew.metadata.mp4.Mp4HandlerFactory.getHandler(Mp4HandlerFactory.java:61)
	at com.drew.metadata.mp4.Mp4BoxHandler.processBox(Mp4BoxHandler.java:82)
	at com.drew.imaging.mp4.Mp4Reader.processBoxes(Mp4Reader.java:58)
	at com.drew.imaging.mp4.Mp4Reader.processBoxes(Mp4Reader.java:56)
	at com.drew.imaging.mp4.Mp4Reader.processBoxes(Mp4Reader.java:56)
	at com.drew.imaging.mp4.Mp4Reader.processBoxes(Mp4Reader.java:56)
	at com.drew.imaging.mp4.Mp4Reader.extract(Mp4Reader.java:42)
	at com.drew.imaging.mp4.Mp4MetadataReader.readMetadata(Mp4MetadataReader.java:57)
	at com.drew.imaging.ImageMetadataReader.readMetadata(ImageMetadataReader.java:178)
	at com.drew.imaging.ImageMetadataReader.readMetadata(ImageMetadataReader.java:125)
	at com.drew.imaging.ImageMetadataReader.readMetadata(ImageMetadataReader.java:205)

Please try this sample video:
https://testing.jalbum.net/bugreport/GOPR0158.MP4

**Comment by davidekholm** [comment]
Thanks!!

**Comment by rewolf** [comment]
@drewnoakes any date for your next Maven release to maven central? Would be nice to source from there. Running into the NPE with GoPro vids on 2.11.0
Thanks!

**Comment by drewnoakes** [comment]
@rewolf please try with 2.12.0.
