### ISSUE TITLE
Stuck when trying to read metadata of one jpg image

### ISSUE THREAD

**Issue by tc350981** [drewnoakes/metadata-extractor#405]
(Please include as much information as possible, and attach a sample image if possible.)
Hi,

We are calling metadata = ImageMetadataReader.readMetadata(imageStream);
And it stuck here, I attached the image and stack trace in this thread. Please let me know if you need more info.

Thanks,
Xu

Some example image:
https://drive.google.com/file/d/1g44066zn7WzrSo7JlFm5oMgqP0jpZNC1/view
https://assets1.ignimgs.com/thumbs/userUploaded/2019/6/9/devolverbtse32019-1560133458336.jpg?fit=bounds&width=1280

"pool-8-thread-5" #1956 prio=5 os_prio=0 tid=0x00007f2768200000 nid=0xdda runnable [0x00007f26405d2000]
   java.lang.Thread.State: RUNNABLE
	at com.adobe.xmp.impl.XMPNode.addChild(Unknown Source)
	at com.adobe.xmp.impl.ParseRDF.addChildNode(Unknown Source)
	at com.adobe.xmp.impl.ParseRDF.rdf_LiteralPropertyElement(Unknown Source)
	at com.adobe.xmp.impl.ParseRDF.rdf_PropertyElement(Unknown Source)
	at com.adobe.xmp.impl.ParseRDF.rdf_PropertyElementList(Unknown Source)
	at com.adobe.xmp.impl.ParseRDF.rdf_NodeElement(Unknown Source)
	at com.adobe.xmp.impl.ParseRDF.rdf_ResourcePropertyElement(Unknown Source)
	at com.adobe.xmp.impl.ParseRDF.rdf_PropertyElement(Unknown Source)
	at com.adobe.xmp.impl.ParseRDF.rdf_PropertyElementList(Unknown Source)
	at com.adobe.xmp.impl.ParseRDF.rdf_NodeElement(Unknown Source)
	at com.adobe.xmp.impl.ParseRDF.rdf_NodeElementList(Unknown Source)
	at com.adobe.xmp.impl.ParseRDF.rdf_RDF(Unknown Source)
	at com.adobe.xmp.impl.ParseRDF.parse(Unknown Source)
	at com.adobe.xmp.impl.XMPMetaParser.parse(Unknown Source)
	at com.adobe.xmp.XMPMetaFactory.parseFromBuffer(Unknown Source)
	at com.adobe.xmp.XMPMetaFactory.parseFromBuffer(Unknown Source)
	at com.drew.metadata.xmp.XmpReader.extract(XmpReader.java:165)
	at com.drew.metadata.xmp.XmpReader.extract(XmpReader.java:145)
	at com.drew.metadata.xmp.XmpReader.extract(XmpReader.java:135)
	at com.drew.metadata.xmp.XmpReader.readJpegSegments(XmpReader.java:124)
	at com.drew.imaging.jpeg.JpegMetadataReader.processJpegSegmentData(JpegMetadataReader.java:134)
	at com.drew.imaging.jpeg.JpegMetadataReader.process(JpegMetadataReader.java:126)
	at com.drew.imaging.jpeg.JpegMetadataReader.readMetadata(JpegMetadataReader.java:77)
	at com.drew.imaging.jpeg.JpegMetadataReader.readMetadata(JpegMetadataReader.java:84)
	at com.drew.imaging.ImageMetadataReader.readMetadata(ImageMetadataReader.java:111)
	at [com.drew.imaging.ImageMetadataReader.readMetadata(ImageMetadataReader.java:89)[](url)](url)

**Comment by tc350981** [comment]
More info: we are using version 2.10.1

**Comment by tc350981** [comment]
Hey Drew, do we have any update for this issue?

Thanks
Xu Wang

**Comment by drewnoakes** [comment]
Do you still see problems in 2.12.0? There was a bug fix around this if I remember correctly.

**Comment by tc350981** [comment]
Thanks for the info. We added a workaround to fix the issue. Let me have a try with the new version.
Thanks

**Comment by drewnoakes** [comment]
I can not reproduce this in the latest version using your sample images.
