### ISSUE TITLE
PanasonicRawWbInfo2Descriptor: Infinite recursion extracting light source

### ISSUE THREAD

**Issue by alpire** [drewnoakes/metadata-extractor#419]
Extracting the light source from PanasonicRawWbInfo2 metadata can lead to an infinite recursion.

**Stacktrace**

```
Exception in thread "main" java.lang.StackOverflowError
        at java.base/java.util.HashMap.hash(HashMap.java:339)
        at java.base/java.util.HashMap.get(HashMap.java:552)
        at com.drew.metadata.Directory.getObject(Directory.java:1100)
        at com.drew.metadata.Directory.getInteger(Directory.java:462)
        at com.drew.metadata.exif.PanasonicRawWbInfo2Descriptor.getWbTypeDescription(PanasonicRawWbInfo2Descriptor.java:65)
        at com.drew.metadata.exif.PanasonicRawWbInfo2Descriptor.getDescription(PanasonicRawWbInfo2Descriptor.java:56)
        at com.drew.metadata.TagDescriptor.getLightSourceDescription(TagDescriptor.java:463)
        at com.drew.metadata.exif.PanasonicRawWbInfo2Descriptor.getWbTypeDescription(PanasonicRawWbInfo2Descriptor.java:69)
        at com.drew.metadata.exif.PanasonicRawWbInfo2Descriptor.getDescription(PanasonicRawWbInfo2Descriptor.java:56)
        at com.drew.metadata.TagDescriptor.getLightSourceDescription(TagDescriptor.java:463)
        at com.drew.metadata.exif.PanasonicRawWbInfo2Descriptor.getWbTypeDescription(PanasonicRawWbInfo2Descriptor.java:69)
        at com.drew.metadata.exif.PanasonicRawWbInfo2Descriptor.getDescription(PanasonicRawWbInfo2Descriptor.java:56)
        at com.drew.metadata.TagDescriptor.getLightSourceDescription(TagDescriptor.java:463)
        at com.drew.metadata.exif.PanasonicRawWbInfo2Descriptor.getWbTypeDescription(PanasonicRawWbInfo2Descriptor.java:69)
        at com.drew.metadata.exif.PanasonicRawWbInfo2Descriptor.getDescription(PanasonicRawWbInfo2Descriptor.java:56)
        at com.drew.metadata.TagDescriptor.getLightSourceDescription(TagDescriptor.java:463)
        at com.drew.metadata.exif.PanasonicRawWbInfo2Descriptor.getWbTypeDescription(PanasonicRawWbInfo2Descriptor.java:69)
        at com.drew.metadata.exif.PanasonicRawWbInfo2Descriptor.getDescription(PanasonicRawWbInfo2Descriptor.java:56)
        at com.drew.metadata.TagDescriptor.getLightSourceDescription(TagDescriptor.java:463)
        ...
```

**Steps to repro**

You can reproduce the issue by downloading [infinite-recursion.txt](https://github.com/drewnoakes/metadata-extractor/files/3418200/infinite-recursion.txt) and running:

```java -cp metadata-extractor-2.12.0.jar com.drew.imaging.ImageMetadataReader infinite-recursion.txt```

The file was generated by fuzzing and is not a valid file format. I used a .txt extension so that github would allow me to upload it.

**Comment by Nadahar** [comment]
As far as I can see, this bug can be triggered quite easily with corrupted/incorrect files. The infinite loop is very small, just 3 steps, but it's unclear to me exactly where the "logical flaw" is and thus where the fix should be done. 

All it takes to achieve this is that the `switch` matches here: https://github.com/drewnoakes/metadata-extractor/blob/ddf21d0164bdb74a759ed2df1f8f380a51cb3db5/Source/com/drew/metadata/exif/PanasonicRawWbInfoDescriptor.java#L48-L56
..so that `getWbTypeDescription(tagType)` is called, that the following returns a value (not null): https://github.com/drewnoakes/metadata-extractor/blob/ddf21d0164bdb74a759ed2df1f8f380a51cb3db5/Source/com/drew/metadata/exif/PanasonicRawWbInfoDescriptor.java#L65
..and that the returned value doesn't match anything in this switch:
https://github.com/drewnoakes/metadata-extractor/blob/ddf21d0164bdb74a759ed2df1f8f380a51cb3db5/Source/com/drew/metadata/TagDescriptor.java#L416-L461

Without a match here, it defaults back to `getDescription(wbtype)` and it's rinse and repeat from there.

**Comment by drewnoakes** [comment]
Thank you very much for this interesting file. It'd definitely be interesting to hear more about how you generated it.

Confirming that the bug is present in the dotnet implementation as well.

**Comment by alpire** [comment]
@drewnoakes: Glad you found the testcase interesting!  It was actually generated automatically using coverage-guided fuzzing while we were testing Apache Tika. I haven't looked at metadata-extractor directly, yet :)

[Fuzzing](http://tiny.cc/why-go-fuzz) is the automated process of finding software bugs by feeding random data into a target program until one of those permutations reveals a flaw. It's been responsible for discovering a large number of security-critical issues found in operating systems, browsers, ...

One of the most important fuzzing advancement has been coverage guidance. A coverage-guided fuzzer gathers coverage information for each random input it tries. If a random input exercises new code, the fuzzer will keep it in a set of interesting inputs. The fuzzer will then generate new inputs by mutating those interesting inputs. 

Coverage-guided fuzzing scales to complex programs. For instance, AFL, a coverage guided fuzzer, has been used to [generate JPEG images out of thin air](https://lcamtuf.blogspot.com/2014/11/pulling-jpegs-out-of-thin-air.html). By fuzzing a JPEG parser with a coverage-guided fuzzer, the fuzzer eventually generates valid JPEG images! The odds of that happening without coverage guidance is infinitesimally small.

Shameless plug: I work on Mayhem, the system that won the [DARPA Cyber Grand Challenge](https://techcrunch.com/2016/08/05/carnegie-mellons-mayhem-ai-takes-home-2-million-from-darpas-cyber-grand-challenge/). We're adapting our bug finding tech to Java and memory-safe languages. We think fuzz testing should be as fundamental as unit testing, and we're actively looking for partners to work with!
