### ISSUE TITLE
NoClassDefFoundError: com/adobe/internal/xmp/XMPException

### ISSUE THREAD

**Issue by 9037568** [drewnoakes/metadata-extractor#501]
When attempting to scan the test image from #396, the distribution jar produces a NoClassDefFoundError.

Command and Stacktrace:

````
java -jar metadata-extractor-2.14.0.jar screencap.png

Exception in thread "main" java.lang.NoClassDefFoundError: com/adobe/internal/xmp/XMPException
        at com.drew.imaging.png.PngMetadataReader.processChunk(PngMetadataReader.java:289)
        at com.drew.imaging.png.PngMetadataReader.readMetadata(PngMetadataReader.java:108)
        at com.drew.imaging.ImageMetadataReader.readMetadata(ImageMetadataReader.java:157)
        at com.drew.imaging.ImageMetadataReader.readMetadata(ImageMetadataReader.java:124)
        at com.drew.imaging.ImageMetadataReader.readMetadata(ImageMetadataReader.java:204)
        at com.drew.imaging.ImageMetadataReader.main(ImageMetadataReader.java:253)
Caused by: java.lang.ClassNotFoundException: com.adobe.internal.xmp.XMPException
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        ... 6 more
````

**Comment by 9037568** [comment]
I was able to fix this by adding the maven-dependency-plugin to the pom.xml.
