### ISSUE TITLE
EXIF Metadata parsing fails with IllegalArgumentException: Input is not a bplist

### ISSUE THREAD

**Issue by swurzinger** [drewnoakes/metadata-extractor#508]
Regression in 2.14.0 (issue does not occur in 2.13.0 or earlier)

Sample code to reproduce (Kotlin):
```kotlin    @Test
    fun parseExifTest() {
        val jpgFile = File("sample.jpg")
        val metadata = ImageMetadataReader.readMetadata(jpgFile)
    }
```

sample.jpg (downsized to 1px * 1px, because image data size doesn't matter):
https://user-images.githubusercontent.com/6787397/95858295-293e4b00-0d5d-11eb-840a-5819da541d6b.jpg

Exception (in 2.14; works in 2.13 or earlier):
```
Input is not a bplist
java.lang.IllegalArgumentException: Input is not a bplist
	at com.drew.metadata.plist.BplistReader.parse(BplistReader.java:68)
	at com.drew.metadata.exif.ExifTiffHandler.processAppleRunTime(ExifTiffHandler.java:369)
	at com.drew.metadata.exif.ExifTiffHandler.customProcessTag(ExifTiffHandler.java:251)
	at com.drew.imaging.tiff.TiffReader.processIfd(TiffReader.java:220)
	at com.drew.metadata.exif.ExifTiffHandler.processMakernote(ExifTiffHandler.java:645)
	at com.drew.metadata.exif.ExifTiffHandler.customProcessTag(ExifTiffHandler.java:207)
	at com.drew.imaging.tiff.TiffReader.processIfd(TiffReader.java:220)
	at com.drew.imaging.tiff.TiffReader.processIfd(TiffReader.java:214)
	at com.drew.imaging.tiff.TiffReader.processTiff(TiffReader.java:78)
	at com.drew.metadata.exif.ExifReader.extract(ExifReader.java:94)
	at com.drew.metadata.exif.ExifReader.extract(ExifReader.java:84)
	at com.drew.metadata.exif.ExifReader.readJpegSegments(ExifReader.java:63)
	at com.drew.imaging.jpeg.JpegMetadataReader.processJpegSegmentData(JpegMetadataReader.java:134)
	at com.drew.imaging.jpeg.JpegMetadataReader.process(JpegMetadataReader.java:126)
	at com.drew.imaging.jpeg.JpegMetadataReader.readMetadata(JpegMetadataReader.java:77)
	at com.drew.imaging.jpeg.JpegMetadataReader.readMetadata(JpegMetadataReader.java:84)
	at com.drew.imaging.ImageMetadataReader.readMetadata(ImageMetadataReader.java:146)
	at com.drew.imaging.ImageMetadataReader.readMetadata(ImageMetadataReader.java:124)
	at com.drew.imaging.ImageMetadataReader.readMetadata(ImageMetadataReader.java:204)
	at com.example.demo.UnitTest.parseExifTest(UnitTest.kt:14)
```

**Comment by mohdharris** [comment]
Facing same issue. This is happening for some images only.

**Comment by BobJohnsonGitHub** [comment]
I downloaded this sample and it looks like malformed data. The "normal" expectation is that it would start with the `bplist\0\0` bytes, but in this sample, that structure appears "deeper" into the array.  Even the data in that offset-bplist did not appear to be parse-able.

Since the `ExifTiffHandler.customProcessTag()` method catches `IOException` while analyzing the BPLIST data, changing from `IllegalArgumentException` to `IOException` should give the desired effect. We would simply see the error message added to the directory while processing.

**Comment by BobJohnsonGitHub** [comment]
Additional note on the data in the image; I extracted the 104-byte array and attempted to preview on a Mac - nothing viewable. The 20-byte section that contained the header was not pre-viewable either.

**Comment by paperboyo** [comment]
> downsized to 1px * 1px, because image data size doesn't matter

This may be totally unrelated, but could I ask how was it resized? Because I haven’t found a way to resize an image without affecting any metadata (eg. an example in https://github.com/drewnoakes/metadata-extractor/issues/435#issue-490266692 was concocted using a hex editor because of that). If anyone knows an easier way to strip/minimise image data, I would love to know!

**Comment by swurzinger** [comment]
@BobJohnsonGitHub what kind of data is that bplist? According to the metadata the image was created by an iPhone XR. I just can tell that version 2.13 did not throw an exception while parsing the metadata and all simple EXIF fields like e.g. orientation or dataTaken were available. Common software like ExifTool, Windows Explorer or XnViewMP also display EXIF data nicely:

![image](https://user-images.githubusercontent.com/6787397/110966676-cd044500-8355-11eb-84ed-3f17ed022a03.png)

![image](https://user-images.githubusercontent.com/6787397/110966952-22d8ed00-8356-11eb-827e-6ca93b712885.png)


@paperboyo I used paint.net, but it did not leave the metadata unmodified, the error just occurs both with the original image and the downscaled one.

**Comment by BobJohnsonGitHub** [comment]
@swurzinger The bplist is supposed to contain data about how long your phone has been running since the last boot (excluding standby time).

@drewnoakes I can pick this up and fix, if you think the use of `IOException` (as noted in https://github.com/drewnoakes/metadata-extractor/issues/508#issuecomment-782725582) is a good approach.

**Comment by drewnoakes** [comment]
@nosnhojbob thanks, that would be great. At the point is thrown, it doesn't really seem like an IOException. Is there a place higher in the call stack where the current exception could be caught and an error added to the Directory?

**Comment by nosnhojbob** [comment]
Please see PR https://github.com/drewnoakes/metadata-extractor/pull/531

I tested with existing images and a local copy of the problematic one.

**Comment by drewnoakes** [comment]
Fixed by @nosnhojbob in #531.

**Comment by charlesritchea** [comment]
@drewnoakes what's the chance of getting a new release with this fix?

**Comment by drewnoakes** [comment]
Released in https://github.com/drewnoakes/metadata-extractor/releases/tag/2.17.0
