### ISSUE TITLE
processAppleRunTime java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Byte

### ISSUE THREAD

**Issue by shalk** [drewnoakes/metadata-extractor#553]
I have debug into the  line. found the values is HashMap<String, char[]>

   byte flags = (Byte)values.get("flags");

https://github.com/drewnoakes/metadata-extractor/blob/2.16.0/Source/com/drew/metadata/exif/ExifTiffHandler.java#L385

```
Exception Stack:
	at com.drew.metadata.exif.ExifTiffHandler.processAppleRunTime(ExifTiffHandler.java:385)
	at com.drew.metadata.exif.ExifTiffHandler.customProcessTag(ExifTiffHandler.java:251)
	at com.drew.imaging.tiff.TiffReader.processIfd(TiffReader.java:220)
	at com.drew.metadata.exif.ExifTiffHandler.processMakernote(ExifTiffHandler.java:645)
	at com.drew.metadata.exif.ExifTiffHandler.customProcessTag(ExifTiffHandler.java:207)
	at com.drew.imaging.tiff.TiffReader.processIfd(TiffReader.java:220)
	at com.drew.imaging.tiff.TiffReader.processIfd(TiffReader.java:214)
	at com.drew.imaging.tiff.TiffReader.processTiff(TiffReader.java:78)
	at com.drew.metadata.exif.ExifReader.extract(ExifReader.java:94)
	at com.drew.metadata.exif.ExifReader.extract(ExifReader.java:84)
	at com.drew.metadata.exif.ExifReader.readJpegSegments(ExifReader.java:63)
	at com.drew.imaging.jpeg.JpegMetadataReader.processJpegSegmentData(JpegMetadataReader.java:134)
	at com.drew.imaging.jpeg.JpegMetadataReader.process(JpegMetadataReader.java:126)
	at com.drew.imaging.jpeg.JpegMetadataReader.readMetadata(JpegMetadataReader.java:77)
	at com.drew.imaging.jpeg.JpegMetadataReader.readMetadata(JpegMetadataReader.java:84)
	at com.drew.imaging.ImageMetadataReader.readMetadata(ImageMetadataReader.java:146)
	at com.drew.imaging.ImageMetadataReader.readMetadata(ImageMetadataReader.java:124)
	at com.drew.imaging.ImageMetadataReader.readMetadata(ImageMetadataReader.java:103)
```

**Comment by drewnoakes** [comment]
@shalk thanks for filing this. Can you share an image that reproduces this issue?

It may be that the value is sometimes a string, and sometimes a `Byte`. I would prefer to only parse when the value is actually a string.

**Comment by nosnhojbob** [comment]
echo @drewnoakes' request for source image. I had only seen similar problems when the BPLIST was malformed or un-parsable. The [top object](https://github.com/drewnoakes/metadata-extractor/blob/61edef50d22bfc6d4f76a2c76d16bdaf171d9e3e/Source/com/drew/metadata/plist/BplistReader.java#L186) is expected to be a map of bytes (a `dict` by the marker).

**Comment by nnl-1** [comment]
Also have an error while reading exif:
java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Long
	at com.drew.metadata.apple.AppleRunTimeReader.processAppleRunTime(AppleRunTimeReader.java:75)
version: 2.18.0
file attached. 
![sample](https://user-images.githubusercontent.com/48063428/172951017-e1e130e3-664a-431a-a4d7-56b0e7d2c91c.jpg)
