### ISSUE TITLE
Support to read metadata from JPEG2000 files

### ISSUE THREAD

**Issue by albfernandez** [drewnoakes/metadata-extractor#562]
Please add support to read metadata from JPEG2000 files.

Sample image relax.jp2 [relax.zip attached](https://github.com/drewnoakes/metadata-extractor/files/7717579/relax.zip) (downloaded from https://www.fnordware.com/j2k/jp2samples.html)

Sample code:
```java
File file = new File("relax.jp2");
try (InputStream is = new FileInputStream(file)) {
    Metadata metadata = ImageMetadataReader.readMetadata(is, file.length());
}
```

Stack trace
```
com.drew.imaging.ImageProcessingException: File format could not be determined
	at com.drew.imaging.ImageMetadataReader.readMetadata(ImageMetadataReader.java:185)
	at com.drew.imaging.ImageMetadataReader.readMetadata(ImageMetadataReader.java:124)
```

**Comment by Hsstone1** [comment]
May I be assigned to this issue to implement this feature?

**Comment by drewnoakes** [comment]
@Hsstone1 thank you for volunteering. There is no need to be assigned before you start working on the feature, though it's a good idea to declare you intention to avoid duplication of effort. In this case I believe you are in the clear.

Reach out here if you have any questions.

**Comment by drewnoakes** [comment]
Once you have completed your analysis, if you'd like to share your thinking then we can validate your approach. This may save you some time overall.
