### ISSUE TITLE
java.lang.ClassNotFoundException: com.adobe.internal.xmp.XMPException error

### ISSUE THREAD

**Issue by Ali1ua** [drewnoakes/metadata-extractor#575]
I am trying to process an image and them use Dom parser to write inside and xml file

**Comment by Ali1ua** [comment]
Exception in thread "main" java.lang.NoClassDefFoundError: com/adobe/internal/xmp/XMPException
	at com.drew.imaging.jpeg.JpegMetadataReader.<clinit>(JpegMetadataReader.java:57)
	at com.drew.imaging.ImageMetadataReader.readMetadata(ImageMetadataReader.java:146)
	at com.drew.imaging.ImageMetadataReader.readMetadata(ImageMetadataReader.java:124)
	at com.drew.imaging.ImageMetadataReader.readMetadata(ImageMetadataReader.java:204)
	at test.testmain.main(testmain.java:68)
Caused by: java.lang.ClassNotFoundException: com.adobe.internal.xmp.XMPException
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 5 more
