### ISSUE TITLE
AppleRunTimeReader.java - (Byte) values.get("flags") class java.lang.String cannot be cast to class java.lang.Byte 

### ISSUE THREAD

**Issue by codeconsole** [drewnoakes/metadata-extractor#576]
file name "HDR Bridge.jpg"

The following code throws an exception:

`AppleRunTimeReader.java`
```
            // https://developer.apple.com/documentation/coremedia/cmtime-u58

            byte flags = (Byte)values.get("flags");

            if ((flags & 0x1) == 0x1) {
                directory.setInt(AppleRunTimeMakernoteDirectory.CMTimeFlags, flags);
                directory.setInt(AppleRunTimeMakernoteDirectory.CMTimeEpoch, (Byte)values.get("epoch"));
                directory.setLong(AppleRunTimeMakernoteDirectory.CMTimeScale, (Long)values.get("timescale"));
                directory.setLong(AppleRunTimeMakernoteDirectory.CMTimeValue, (Long)values.get("value"));
            }
```

`byte flags = (Byte)values.get("flags");` is causing

```
Caused by: java.lang.ClassCastException: class java.lang.String cannot be cast to class java.lang.Byte (java.lang.String and java.lang.Byte are in module java.base of loader 'bootstrap')
	at com.drew.metadata.apple.AppleRunTimeReader.processAppleRunTime(AppleRunTimeReader.java:70)
	at com.drew.metadata.apple.AppleRunTimeReader.extract(AppleRunTimeReader.java:34)
	at com.drew.metadata.exif.ExifTiffHandler.customProcessTag(ExifTiffHandler.java:242)
	at com.drew.imaging.tiff.TiffReader.processIfd(TiffReader.java:220)
	at com.drew.metadata.exif.ExifTiffHandler.processMakernote(ExifTiffHandler.java:591)
	at com.drew.metadata.exif.ExifTiffHandler.customProcessTag(ExifTiffHandler.java:205)
```

where values.get("flags") is returning a the String "1" 

There is also an issue with `(Byte)values.get("epoch")`, `(Long)values.get("timescale")`, and `(Long)values.get("value"))`

values.get("epoch") is returning the String "0"
values.get("timescale") is returning the String "1000000000"
values.get("value") is returning the String "  1963812590699"

so it appears all the values read are String when the expectation is that they are not.

Internal Reference: 5493705690578944 (In case their are follow up questions)

**Comment by codeconsole** [comment]
Perhaps this is related? 
https://github.com/drewnoakes/metadata-extractor/issues/553

**Comment by codeconsole** [comment]
I have numerous example images I can provide privately.
