### ISSUE TITLE
Is `metadata-extractor` compatible with Quarkus native?

### ISSUE THREAD

**Issue by bpsbits-org** [drewnoakes/metadata-extractor#688]
Is `metadata-extractor` compatible with Quarkus native?

I'm trying to use `metadata-extractor` with Quarkus native, but getting `java.lang.InstantiationException` error:

```
java.lang.RuntimeException: java.lang.InstantiationException: com.drew.metadata.exif.ExifIFD0Directory
        at com.drew.metadata.tiff.DirectoryTiffHandler.pushDirectory(DirectoryTiffHandler.java:65)
        at com.drew.metadata.exif.ExifTiffHandler.setTiffMarker(ExifTiffHandler.java:79)
        at com.drew.imaging.tiff.TiffReader.processTiff(TiffReader.java:65)
        at com.drew.metadata.exif.ExifReader.extract(ExifReader.java:94)
        at com.drew.metadata.exif.ExifReader.extract(ExifReader.java:84)
        at com.drew.metadata.exif.ExifReader.readJpegSegments(ExifReader.java:63)
        at com.drew.imaging.jpeg.JpegMetadataReader.processJpegSegmentData(JpegMetadataReader.java:134)
        at com.drew.imaging.jpeg.JpegMetadataReader.process(JpegMetadataReader.java:126)
        at com.drew.imaging.jpeg.JpegMetadataReader.readMetadata(JpegMetadataReader.java:77)
        at com.drew.imaging.jpeg.JpegMetadataReader.readMetadata(JpegMetadataReader.java:84)
        at com.drew.imaging.ImageMetadataReader.readMetadata(ImageMetadataReader.java:146)
        at com.drew.imaging.ImageMetadataReader.readMetadata(ImageMetadataReader.java:124)
```

**Comment by bpsbits-org** [comment]
```
java.lang.RuntimeException: java.lang.InstantiationException: com.drew.metadata.exif.ExifSubIFDDirectory
		at com.drew.metadata.tiff.DirectoryTiffHandler.pushDirectory(DirectoryTiffHandler.java:65)
		at com.drew.metadata.exif.ExifTiffHandler.tryEnterSubIfd(ExifTiffHandler.java:98)
		at com.drew.imaging.tiff.TiffReader.processIfd(TiffReader.java:211)
		at com.drew.imaging.tiff.TiffReader.processTiff(TiffReader.java:78)
		at com.drew.metadata.exif.ExifReader.extract(ExifReader.java:94)
		at com.drew.metadata.exif.ExifReader.extract(ExifReader.java:84)
		at com.drew.metadata.exif.ExifReader.readJpegSegments(ExifReader.java:63)
		at com.drew.imaging.jpeg.JpegMetadataReader.processJpegSegmentData(JpegMetadataReader.java:134)
		at com.drew.imaging.jpeg.JpegMetadataReader.process(JpegMetadataReader.java:126)
		at com.drew.imaging.jpeg.JpegMetadataReader.readMetadata(JpegMetadataReader.java:77)
		at com.drew.imaging.jpeg.JpegMetadataReader.readMetadata(JpegMetadataReader.java:84)
		at com.drew.imaging.ImageMetadataReader.readMetadata(ImageMetadataReader.java:146)
		at com.drew.imaging.ImageMetadataReader.readMetadata(ImageMetadataReader.java:124)
		at com.drew.imaging.ImageMetadataReader.readMetadata(ImageMetadataReader.java:204)
		...
		at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
		at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:141)
		at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:147)
		at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:635)
		at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2516)
		at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2495)
		at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1521)
		at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:11)
		at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:11)
		at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
		at java.base@22.0.2/java.lang.Thread.runWith(Thread.java:1583)
		at java.base@22.0.2/java.lang.Thread.run(Thread.java:1570)
		at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:853)
		at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:829)
Caused by: java.lang.InstantiationException: com.drew.metadata.exif.ExifSubIFDDirectory
		at java.base@22.0.2/java.lang.Class.newInstance(DynamicHub.java:749)
		at com.drew.metadata.tiff.DirectoryTiffHandler.pushDirectory(DirectoryTiffHandler.java:63)
		... 30 more
Caused by: java.lang.NoSuchMethodException: com.drew.metadata.exif.ExifSubIFDDirectory.<init>()
		at java.base@22.0.2/java.lang.Class.checkExecutable(DynamicHub.java:1101)
		at java.base@22.0.2/java.lang.Class.checkConstructor(DynamicHub.java:1082)
		at java.base@22.0.2/java.lang.Class.getConstructor0(DynamicHub.java:1272)
		at java.base@22.0.2/java.lang.Class.newInstance(DynamicHub.java:736)
		... 31 more
```

**Comment by bpsbits-org** [comment]
## Issue solved

### Caused by 

`ExifSubIFDDirectory` is loaded via reflection, but quarkus native doesnt have info about initializer.

### Solution

The way how to get it to work in Quarkus Native:

add file `reflect-config.json` into your project:

```
src/main/resources/reflect-config.json
```

Add following items into this file:

```json
[
  {
    "name": "com.drew.metadata.Directory",
    "allDeclaredConstructors": true,
    "allPublicConstructors": true,
    "allDeclaredMethods": true,
    "allPublicMethods": true,
    "allDeclaredFields": true,
    "allPublicFields": true
  },
  {
    "name": "com.drew.metadata.ErrorDirector",
    "allDeclaredConstructors": true,
    "allPublicConstructors": true,
    "allDeclaredMethods": true,
    "allPublicMethods": true,
    "allDeclaredFields": true,
    "allPublicFields": true
  },
  {
    "name": "com.drew.metadata.exif.ExifDirectoryBase",
    "allDeclaredConstructors": true,
    "allPublicConstructors": true,
    "allDeclaredMethods": true,
    "allPublicMethods": true,
    "allDeclaredFields": true,
    "allPublicFields": true
  },
  {
    "name": "com.drew.metadata.exif.ExifIFD0Directory",
    "allDeclaredConstructors": true,
    "allPublicConstructors": true,
    "allDeclaredMethods": true,
    "allPublicMethods": true,
    "allDeclaredFields": true,
    "allPublicFields": true
  }
]
```
