### ISSUE TITLE
IPTC extraction throws error on valid image (2.7.0 regression)

### ISSUE THREAD

**Issue by theefer** [drewnoakes/metadata-extractor#72]
I've tried upgrading our system to 2.7.0 as it fixes encoding issues we're seeing with some images. However, it appears that 2.7.0 fails with an exception when trying to read the IPTC metadata of an image that was previously being processed fine on 2.6.2.

This is the stacktrace:

```
java.lang.NullPointerException: cannot set a null String
        at com.drew.metadata.Directory.setString(Directory.java:245)
        at com.drew.metadata.iptc.IptcReader.processTag(IptcReader.java:149)
        at com.drew.metadata.iptc.IptcReader.extract(IptcReader.java:131)
        at com.drew.metadata.photoshop.PhotoshopReader.extract(PhotoshopReader.java:117)
        at com.drew.metadata.photoshop.PhotoshopReader.extract(PhotoshopReader.java:58)
        at com.drew.imaging.jpeg.JpegMetadataReader.processJpegSegmentData(JpegMetadataReader.java:127)
        at com.drew.imaging.jpeg.JpegMetadataReader.process(JpegMetadataReader.java:117)
        at com.drew.imaging.jpeg.JpegMetadataReader.readMetadata(JpegMetadataReader.java:68)
        at com.drew.imaging.jpeg.JpegMetadataReader.readMetadata(JpegMetadataReader.java:75)
        at com.drew.imaging.ImageMetadataReader.readMetadata(ImageMetadataReader.java:101)
        at com.drew.imaging.ImageMetadataReader.readMetadata(ImageMetadataReader.java:156)
```

And here is the offending image (Reuters image, resized to a minuscule size so hopefully no issue with copyright):

![broken-metadata](https://cloud.githubusercontent.com/assets/36964/5841005/744c30fa-a191-11e4-9355-0de7790476a2.jpg)

**Comment by Odrahcyr** [comment]
Already fixed. Tested with current development branch. Dupilcate of #59.

**Comment by theefer** [comment]
Ah great. #59 was open by a colleague, so really I should have checked with him :-)

Is there any ETA on pushing 2.7.1 to maven central? We're keen to upgrade to 2.7.0 to fix the encoding issue but I'd be reluctant to rely on a dev version...

If there's anything we can help with to make it happen, please let us know!

Thanks for the quick reply!

**Comment by theefer** [comment]
Sorry just reading https://github.com/drewnoakes/metadata-extractor/issues/69 now...
