### ISSUE TITLE
ProcessAllImagesInFolderUtility FileNotFoundException for images with *.txt suffix (i.e. jpg.txt,png.txt, etc.)

### ISSUE THREAD

**Issue by Odrahcyr** [drewnoakes/metadata-extractor#77]
If ProcessAllImagesInFolderUtility encounters a file like "example.jpg.txt" it will throw an FileNotFoundException. This issue is most likely related to the recent changes in ProcessAllImagesInFolderUtility.

Stacktrace:

	at java.io.FileOutputStream.open(Native Method)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:194)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:116)
	at java.io.FileWriter.<init>(FileWriter.java:61)
	at com.drew.tools.ProcessAllImagesInFolderUtility$TextFileOutputHandler.openWriter(ProcessAllImagesInFolderUtility.java:282)
	at com.drew.tools.ProcessAllImagesInFolderUtility$TextFileOutputHandler.onExtracted(ProcessAllImagesInFolderUtility.java:220)
	at com.drew.tools.ProcessAllImagesInFolderUtility.processDirectory(ProcessAllImagesInFolderUtility.java:116)
	at com.drew.tools.ProcessAllImagesInFolderUtility.processDirectory(ProcessAllImagesInFolderUtility.java:102)
	at com.drew.tools.ProcessAllImagesInFolderUtility.processDirectory(ProcessAllImagesInFolderUtility.java:102)
	at com.drew.tools.ProcessAllImagesInFolderUtility.processDirectory(ProcessAllImagesInFolderUtility.java:102)
	at com.drew.tools.ProcessAllImagesInFolderUtility.processDirectory(ProcessAllImagesInFolderUtility.java:102)
	at com.drew.tools.ProcessAllImagesInFolderUtility.main(ProcessAllImagesInFolderUtility.java:79)

**Comment by drewnoakes** [comment]
I cannot reproduce this. Seems the exception's related to the writing of the metadata text file.

The call to `FileWriter`'s constructor is raising the exception, yet its docs say the only raised exception is `IOException` which occurs:

> if the named file exists but is a directory rather than a regular file, does not exist but cannot be created, or cannot be opened for any other reason

Can you explain how to repro this?

**Comment by Odrahcyr** [comment]
Oh, I had changed the directory permissions to read-only for whatever reason. Thus ProcessAllImagesInFolderUtility wasn't able to override the old .txt files.

**Comment by drewnoakes** [comment]
Good news. Thinking of releasing 2.7.1 tomorrow, so let me know if you
think of any reason to hold off.
